spec:
  inputs:
    sstate-mirror:
      type: boolean
      default: true
      description: Use shared sstate mirror
    downloads-mirror:
      type: boolean
      default: true
      description: Use shared downloads mirror

---

include:
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/workflow@1
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/build@1
    inputs:
      image-name: ghcr.io/siemens/kas/kas:5.2-debian-bookworm
      sstate-mirror: $[[ inputs.sstate-mirror ]]
      downloads-mirror: $[[ inputs.downloads-mirror ]]
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/lava@1

stages:
  - ci-kas
  - build
  - test

.ci_matrix: &ci_matrix
  parallel:
    matrix:
      - KAS_MACHINE:
        - grinn-genio-510-sbc
        - grinn-genio-700-sbc
        - grinn-genio-700-evb

build:
  <<: *ci_matrix
  variables:
    KAS_TARGET: rity-demo-image
  artifacts:
    expire_in: 1d
    paths:
      - build.log
      - build/tmp/deploy/images/*/*.tar.zst
      - build/tmp/deploy/images/*/fitImage-*.bin

lava:
  <<: *ci_matrix
  needs:
    - lava-pre
    - job: build
      artifacts: true
      parallel:
        matrix:
          - KAS_MACHINE: ['$[[ matrix.KAS_MACHINE ]]']
