spec:
  inputs:
    sstate-mirror:
      type: boolean
      default: true
      description: Use shared sstate mirror
    downloads-mirror:
      type: boolean
      default: true
      description: Use shared downloads mirror
    git-mirror:
      type: boolean
      default: true
      description: Use git mirrors
    deploy-public:
      type: boolean
      default: false
      description: Deploy to public HTTP server

---

include:
  - component: $CI_SERVER_FQDN/grinn/ci/ci-lib/deploy-public@deploy-public
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/workflow@2
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/build@2
    inputs:
      image-name: ghcr.io/siemens/kas/kas:5.2-debian-bookworm
      sstate-mirror: $[[ inputs.sstate-mirror ]]
      downloads-mirror: $[[ inputs.downloads-mirror ]]
      git-mirror: $[[ inputs.git-mirror ]]
  - component: $CI_SERVER_FQDN/grinn/ci/yocto/kas/lava@1

stages:
  - ci-kas
  - build
  - test
  - deploy

.ci_matrix: &ci_matrix
  parallel:
    matrix:
      - KAS_MACHINE:
        - grinn-genio-510-sbc
        - grinn-genio-700-sbc
        - grinn-genio-700-evb

build:
  <<: *ci_matrix
  variables:
    KAS_TARGET: rity-demo-image
  artifacts:
    expire_in: 1d
    paths:
      - build.log
      - build/tmp/deploy/images/*/*.tar.zst
      - build/tmp/deploy/images/*/fitImage-*.bin

lava:
  <<: *ci_matrix
  needs:
    - lava-pre
    - job: build
      artifacts: true
      parallel:
        matrix:
          - KAS_MACHINE: ['$[[ matrix.KAS_MACHINE ]]']

deploy-public:
  <<: *ci_matrix
  variables:
    KAS_TARGET: rity-demo-image
  rules:
    - if: $[[ inputs.deploy-public ]] == "true"
  needs:
    - job: build
      artifacts: true
      parallel:
        matrix:
          - KAS_MACHINE: ['$[[ matrix.KAS_MACHINE ]]']
  script:
    - |
      DATE=${CI_PIPELINE_CREATED_AT%%T*}
      COMMIT=${CI_COMMIT_SHA:0:10}
      FILE_NAME=$KAS_MACHINE-default-$DATE-$COMMIT.tar.zst

    - mv build/tmp/deploy/images/$KAS_MACHINE/$KAS_TARGET-$KAS_MACHINE.aiotflash.tar.zst $FILE_NAME
    - ci-lib/bin/deploy-public --upload-path genio/$DATE $FILE_NAME
