device_type: {{ job.KAS_MACHINE }}
job_name: "{{ job.KAS_TARGET }}-{{ job.KAS_MACHINE }}-{{ job.CI_PIPELINE_ID }}"
timeouts:
  job:
    minutes: 60
  actions:
    http-download:
      minutes: 30
    download-retry:
      minutes: 35
priority: medium
visibility: public

actions:
  - command:
      name: pre_power_command
  - command:
      name: power_on
  - deploy:
      timeout:
        minutes: 10
      to: flasher
      images:
        image:
          url: "{{ job.CI_API_V4_URL }}/projects/{{ job.CI_PROJECT_ID }}/jobs/{{ job.BUILD_JOB_ID }}/artifacts/build/tmp/deploy/images/{{ job.KAS_MACHINE }}/{{ job.KAS_TARGET }}-{{ job.KAS_MACHINE }}.rootfs.aiotflash.tar.zst?job_token={{ job.CI_JOB_TOKEN }}"
          compression: zstd
          archive: tar
  - deploy:
      timeout:
        minutes: 40
      to: tftp
      kernel:
        url: "{{ job.CI_API_V4_URL }}/projects/{{ job.CI_PROJECT_ID }}/jobs/{{ job.BUILD_JOB_ID }}/artifacts/build/tmp/deploy/images/{{ job.KAS_MACHINE }}/fitImage-{{ job.KAS_MACHINE }}.bin?job_token={{ job.CI_JOB_TOKEN }}"
      nfsrootfs:
        url: "{{ job.CI_API_V4_URL }}/projects/{{ job.CI_PROJECT_ID }}/jobs/{{ job.BUILD_JOB_ID }}/artifacts/build/tmp/deploy/images/{{ job.KAS_MACHINE }}/{{ job.KAS_TARGET }}-{{ job.KAS_MACHINE }}.rootfs.tar.zst?job_token={{ job.CI_JOB_TOKEN }}"
        compression: zstd

  - boot:
      method: u-boot
      timeout:
        minutes: 10
      commands:
        - setenv autoload no
        - dhcp
        - "" # Force a prompt return
        - setenv serverip {SERVER_IP}
        - setenv kerneladdr 0x4A000000
        - setenv loadaddr 0x4A000000
        - setenv bootargs "console=ttyS0,921600 root=/dev/nfs rw nfsroot={SERVER_IP}:{NFSROOTFS},v3,tcp ip=dhcp rootwait"
        - tftpboot {KERNEL}
        - "" # Force a prompt return
        - bootm ${kerneladdr}${boot_conf}
      soft_reboot: reset
      auto_login:
        login_prompt: "login:.*"
        username: root
      prompts:
        - "root@{{ job.KAS_MACHINE }}:~#"
        - "root@.*:~#"
        - "~#"
      failure_message: 'Kernel panic|Oops(?: -|:)|Unable to handle kernel|Internal error|BUG:|Call trace:|segfault'

  - test:
      timeout:
        minutes: 30
      definitions:
        - from: git
          repository: git@gitlab.grinndev.ovh:grinn/ci/lava/lava-test-definitions.git
          path: automated/linux/ethernet/ethernet-test.yaml
          name: ethernet-test
        - from: git
          repository: git@gitlab.grinndev.ovh:grinn/ci/lava/lava-test-definitions.git
          path: automated/linux/optiga/optiga-test.yaml
          name: optiga-test
          parameters:
            OPTIGA_I2C_BUS: "/dev/i2c-6"
            DEVICE: "{{ job.KAS_MACHINE }}"
        - from: git
          repository: git@gitlab.grinndev.ovh:grinn/ci/lava/lava-test-definitions.git
          path: automated/linux/usb/usb-test.yaml
          name: usb-test
          parameters:
            DEVICE: "{{ job.KAS_MACHINE }}"
