header:
  version: 14

distro: rity-demo
target: rity-demo-image
machine: unset

local_conf_header:
  meta-grinn-genio: |
    PACKAGE_CLASSES ?= "package_ipk"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
    USER_CLASSES ?= "buildstats"
    PATCHRESOLVE = "noop"

    BB_DISKMON_DIRS ??= "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"

    PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
    SKIP_META_SECURITY_SANITY_CHECK = "1"
    CONF_VERSION = "2"
    LICENSE_FLAGS_ACCEPTED = "commercial commercial_libav commercial_x264"
    IMAGE_ROOTFS_EXTRA_SPACE = "200000"
    TFLITE_PREBUILT = "0"

bblayers_conf_header:
  meta-grinn-genio: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

repos:
  meta-arm:
    url: https://git.yoctoproject.org/meta-arm
    commit: a81c19915b5b9e71ed394032e9a50fd06919e1cd
    branch: scarthgap
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-asix:
    url: https://gitlab.com/asix_official/ax88179_series/mtk_genio/yocto/rity/meta-asix
    commit: d2551230c1fc4a0bebd2d2f0b5e3e9a0aee678e2
    branch: main

  meta-browser:
    url: https://gitlab.collabora.com/mediatek/aiot/rity/meta-browser
    commit: f50e7319de63d6c36810cfbfac417e18233d430e
    branch: mediatek/scarthgap
    layers:
      meta-chromium:

  meta-clang:
    url: https://github.com/kraj/meta-clang
    commit: b4532c75af7b1957b10cc4d5377fc4cfa0b1cbf6
    branch: scarthgap-clang20

  meta-lts-mixins:
    url: https://git.yoctoproject.org/meta-lts-mixins
    commit: 96deb45139df027473faf0938fe006d33c45c375
    branch: scarthgap/rust

  meta-mediatek-bluedroid:
    url: https://gitlab.com/mediatek/aiot/rity/meta-mediatek-bluedroid
    commit: bfb2c6f718b76465e940533b85089eea25f4b6c6
    branch: scarthgap

  meta-mediatek-bsp:
    url: https://gitlab.com/mediatek/aiot/rity/meta-mediatek-bsp
    commit: 24dad2a50ad27ea2d0c2e65d8389e5ae36e2f1e6
    branch: release/rity-scarthgap

  meta-mediatek-demo:
    url: https://gitlab.com/mediatek/aiot/rity/meta-mediatek-demo
    commit: 815a43e8c1d5850c7d4d633d0dd4d532186b859f
    branch: release/rity-scarthgap

  meta-mediatek-tsn:
    url: https://gitlab.com/mediatek/aiot/rity/meta-mediatek-tsn
    commit: 9e780f424ba2b1f56090113e96acf8f90aabf0ed
    branch: release/rity-scarthgap

  meta-nn:
    url: https://gitlab.com/mediatek/aiot/rity/meta-nn
    commit: 9bf72cf539cec4ab6ce5c4ae64daa201af889875
    branch: release/rity-scarthgap

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    commit: ae7dfb12245c7f9b9a353499e2688015bd4e6413
    branch: scarthgap
    layers:
      meta-multimedia:
      meta-networking:
      meta-oe:
      meta-perl:
      meta-python:

  meta-rity:
    url: https://gitlab.com/mediatek/aiot/rity/meta-rity
    commit: 4542a23fdd0c3384230efa73e402d597f10425c7
    branch: release/rity-scarthgap
    layers:
      meta:
      meta-rity-bringup:
      meta-rity-demo:

  meta-security:
    url: https://git.yoctoproject.org/meta-security
    commit: b13f1705d723650de61277670c8a76aadea4cfdd
    branch: scarthgap

  meta-tensorflow:
    url: https://git.yoctoproject.org/meta-tensorflow.git
    commit: eeee54cfa3c51c1fd99604a0d5f173096bdcf1da
    branch: scarthgap

  poky:
    url: https://git.yoctoproject.org/poky
    commit: d4576e3c081a7ee7b57d48421c4c4f491cb4defe
    branch: scarthgap
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-grinn-genio:
    layers:
      meta-grinn-genio-bsp:
      meta-grinn-genio-fixes:
